# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=500)),
                ('years_of_experience', models.FloatField()),
                ('technologies', models.CharField(max_length=1000)),
                ('current_organisation', models.CharField(max_length=500)),
                ('current_CTC', models.FloatField()),
                ('expected_CTC', models.FloatField()),
                ('notice_period', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
