# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='application_status',
            field=models.CharField(choices=[(True, 'Accept'), (False, 'Reject')], default='', max_length=100),
        ),
    ]
