# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_recruit_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='application_status',
            field=models.CharField(choices=[(True, 'Accept'), (False, 'Reject')], default='', max_length=100, null=True),
        ),
    ]
