# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_auto_20180727_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruit',
            name='application_status',
            field=models.CharField(choices=[('select', 'select'), (True, 'Accept'), (False, 'Reject')], default='select', max_length=100, null=True),
        ),
    ]
